Adjustments for node in travis
We install node using an approach from nodejs.org:

see https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions

However that still gives us only node 4.1.2 (!?).

Hence the error log at travis complained:
> Error: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

So we ensure that the .eslintrc.js runs explicitly in strict mode.